date


mkdir build
cd build


RUN_NUM=2
THREAD_NUM=$(numactl --hardware | awk '/node 0 cpus:/ {print (NF-3)/2}')
THREAD_NUM=$((2 * THREAD_NUM))

# # ab_hash
# AB_HIGH_THREAD_NUM=8
# AB_PRT=0.95
AB_HIGH_THREAD_NUM=16
# AB_PRT=0.90
AB_PRT=0.85
# # mask-6
# DAHA_SYMB_THRES=6000000
# DAHA_NUMC_THRES=800000
# mask-1
DAHA_SYMB_THRES=11000000
DAHA_NUMC_THRES=2500000

# # ab_hsersc
AB_HIGH_THREAD_NUM=22
AB_PRT=0.85
# # mask-6
# DAHA_SYMB_THRES=5000000
# DAHA_NUMC_THRES=340000
# # mask-1
DAHA_SYMB_THRES=7000000
DAHA_NUMC_THRES=2100000


# # ab_hybacc
AB_HIGH_THREAD_NUM=22
AB_PRT=0.85
# # mask-6
# DAHA_SYMB_THRES=5000000
# DAHA_NUMC_THRES=340000
# # mask-1
DAHA_SYMB_THRES=7000000
DAHA_NUMC_THRES=2100000



# # # # TAMU
# DAB_ACC_THRES=1.116000
# # # webbase-1M
# AB_ACC_THRES=1.00001


# # # RMAT
# # mask-6
# AB_ACC_THRES=1.50
# # mask-1
AB_ACC_THRES=2.116




# ## for comparison against LPT and SIMP
# AB_PRT=0.85
# # mask-6
# DAHA_SYMB_THRES=5000000
# DAHA_NUMC_THRES=340000
# # # ab_hybacc
# AB_HIGH_THREAD_NUM=16 	# SIMP.AB_HIGH_THREAD_NUM=15
# # # ab_hash
# # AB_HIGH_THREAD_NUM=14 	# SIMP.AB_HIGH_THREAD_NUM=12
# # # ab_hsersc
# # AB_HIGH_THREAD_NUM=20 	# SIMP.AB_HIGH_THREAD_NUM=24




cmake .. -DTHREAD_NUM=$THREAD_NUM -DUSE_HYPERTHREADING=true  \
	-DNUMA_MASK_VAL=1 -DUSE_WEIGHTED_INTERLEAVING=true -DUSE_INTERLEAVING=false \
	-DCSRC_WRITE_OPTIMIZED=false -DCSRC_PREPOPULATED=false -DUSE_HUGE=false \
	-DMEMSV=false -DMEMSVB=false -DMEM_MON=false \
	-DAB_HIGH_THREAD_NUM=$AB_HIGH_THREAD_NUM -DAB_SIZE=524288 -DAB_MIN_NUM=32768 \
	-DAB_LPT=false -DAB_SIMP=false -DAB_PRT=$AB_PRT -DAB_MAXFLP=false \
	-DAB_DNR=true \
	-DAB_HYOPT=false -DAB_SYMB_THRES=66.0 -DAB_NUMC_THRES=1.50 \
	-DDAHA=true -DDAHA_REAR=true \
	-DDAHA_QUANTILE=0.99 \
	-DDAHA_SYMB_THRES=$DAHA_SYMB_THRES \
	-DDAHA_NUMC_THRES=$DAHA_NUMC_THRES \
	-DDAHA_SPMV_THRES=$DAHA_SPMV_THRES \
	-DDAHA_SPMM_THRES=$DAHA_SPMM_THRES \
	-DAB_ACC_THRES=$AB_ACC_THRES \
	-DDN_MIN=256 \
	-DGUD_ALPHA=0.5 -DGUD_MIN=256 -DHYB_THRES=0.95 \
	-DHASH_CONSTANT=2654435761 	-DSPMM_B_K=512 \
	-DMKL_SORT=false -DMKL_ENHANCE=false \
	-DRUN_NUM=$RUN_NUM -DIN_TAMU=false -DIN_GROUPBY=false -DIN_SSJ=false \
	-DUSE_PAPI=false -DIN_INSP=false -DIN_STATS=false -DIN_VERIFY=false \
	-DIN_DEBUG=false -DIN_EXAMINE=false \
	-DCFG_PATH=config/mc/mxc0.cfg

# -DCF_MARK_0=1.7 -DCF_MARK_1=2.2
# -DCF_MARK_0=100.0 -DCF_MARK_1=1.85
# -DCF_MARK_0=1.15 -DCF_MARK_1=1.85


make -j $(( $(nproc) / 16 ))
cd ..


date